### ISSUE TITLE
Test failing due to clock precision

### ISSUE THREAD

**Issue by kobbe** [magnusmickelsson/pokeraidbot#11]
When I run the tests, some tests in pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest fails. The problem seems to be that I get a more accurate clock result than H2 stores in the database. I have not tested if the same problem happen with the other types of databases. I am running windows 10 with JDK 14.

I am unsure of how to fix the problem. If the RaidEntity or RaidEntityRepositoryTest should strip some clock precision for example.

```
-------------------------------------------------------------------------------
Test set: pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 5.718 sec <<< FAILURE! - in pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest
createWithGroup(pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest)  Time elapsed: 0.069 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <RaidEntity{id='id1', pokemon='Mupp', endOfRaid=2020-05-17T21:25:32.387514800, gym='Thegym', creator='Theuser', region='Theregion', ex=false}>
     but: was <RaidEntity{id='id1', pokemon='Mupp', endOfRaid=2020-05-17T21:25:32.387515, gym='Thegym', creator='Theuser', region='Theregion', ex=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest.createWithGroup(RaidEntityRepositoryTest.java:61)

createAndGet(pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest)  Time elapsed: 0.028 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <RaidEntity{id='id1', pokemon='Mupp', endOfRaid=2020-05-17T21:25:32.441370500, gym='Thegym', creator='Theuser', region='Theregion', ex=false}>
     but: was <RaidEntity{id='id1', pokemon='Mupp', endOfRaid=2020-05-17T21:25:32.441371, gym='Thegym', creator='Theuser', region='Theregion', ex=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest.createAndGet(RaidEntityRepositoryTest.java:78)

createEx(pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest)  Time elapsed: 0.015 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <RaidEntity{id='id1', pokemon='Mupp', endOfRaid=2020-05-17T21:25:35.901773400, gym='Thegym', creator='Theuser', region='Theregion', ex=true}>
     but: was <RaidEntity{id='id1', pokemon='Mupp', endOfRaid=2020-05-17T21:25:35.901773, gym='Thegym', creator='Theuser', region='Theregion', ex=true}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at pokeraidbot.infrastructure.jpa.RaidEntityRepositoryTest.createEx(RaidEntityRepositoryTest.java:89)

```

**Comment by magnusmickelsson** [comment]
Will have a look at this, but since the Heroku container doesn't use the newest JDK I am not going to use it locally when testing and developing, so the easiest workaround is to have a second JDK that you use for this particular project.

**Comment by magnusmickelsson** [comment]
Finally got around to trying this out, solved locally now with Java 14, via less precision of input LocalDateTime values.
